[mgr]
# Rangerのデフォルト比率に合わせる
ratio = [ 1, 3, 4 ]

# 親ディレクトリの自動プレビューなどが不要ならここで調整
# show_hidden = false
# sort_by = "natural"

[plugin]
prepend_previewers = [
    # folder名が "fast-audio.yazi" なら、run = "fast-audio" と書きます
    { mime = "audio/*", run = "fast-audio" },
]

[opener]
# raner に従い rifle という名前にしました2025/12/02 16:20
rifle_block  = [{ run = '~/.config/yazi/scripts/rifle.sh "$1"', block = true, desc = "rifle (block)" }]
rifle_orphan = [{ run = '~/.config/yazi/scripts/rifle.sh "$1"', block = false, orphan = true, desc = "rifle (orphan)" }]

[open]
rules = [
    { mime = "audio/*", use = "rifle_orphan" },
    { mime = "video/*", use = "open" },
    { mime = "image/*", use = "open" },
    { mime = "*", use = "rifle_block" },
]
