[mgr]
# Rangerのデフォルト比率に合わせる
ratio = [ 1, 3, 4 ]

# 親ディレクトリの自動プレビューなどが不要ならここで調整
# show_hidden = false
# sort_by = "natural"

[opener]
my_opener_block  = [{ run = '~/.config/yazi/scripts/my-opener.sh "$1"', block = true, desc = "My opener (block)" }]
my_opener_orphan = [{ run = '~/.config/yazi/scripts/my-opener.sh "$1"', block = false, orphan = true, desc = "My opener (orphan)" }]

[open]
rules = [
    { mime = "audio/*", use = "my_opener_orphan" },
    { mime = "video/*", use = "open" },
    { mime = "image/*", use = "open" },
    { mime = "*", use = "my_opener_block" },
]
