[mgr]
# Rangerのデフォルト比率に合わせる
ratio = [ 1, 3, 4 ]

# 親ディレクトリの自動プレビューなどが不要ならここで調整
# show_hidden = false
# sort_by = "natural"

[plugin]
prepend_previewers = [
    # folder名が "fast-audio.yazi" なら、run = "fast-audio" と書きます
    { mime = "audio/*", run = "fast-audio" },
]

[opener]
# raner に従い scope という名前にしました2025/11/29  2:12
scope_block  = [{ run = '~/.config/yazi/scripts/scope.sh "$1"', block = true, desc = "scope (block)" }]
scope_orphan = [{ run = '~/.config/yazi/scripts/scope.sh "$1"', block = false, orphan = true, desc = "scope (orphan)" }]

[open]
rules = [
    { mime = "audio/*", use = "scope_orphan" },
    { mime = "video/*", use = "open" },
    { mime = "image/*", use = "open" },
    { mime = "*", use = "scope_block" },
]
